//src/app/layot.jsx
import Sidebar from "@/components/Sidebar/Sidebar";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { AuthProvider } from "@/components/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { DialogProvider } from "@/contexts/DialogContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <DialogProvider>
            <main>
              {children}
              <Toaster />
            </main>
          </DialogProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
